### ISSUE TITLE
Pluggable HttpClient (AppEngine compatibility)

### ISSUE THREAD

**Issue by ben-manes** [anurag/stripe-scala#3]
I think that the current usage of Apache HttpClient is not compatible with Google AppEngine, resulting in the error below. Details of how to make client compatible is described at:
http://code.google.com/p/googleappengine/wiki/WillItPlayInJava

The cleanest approach may be to use the cake pattern to allow changing the default http client. Another approach may be to define a provider, defaulting to the current implementation, that can set. Either would allow the client to swap out the client and provide one configured to work in their environment.

java.lang.NoClassDefFoundError: Could not initialize class com.google.apphosting.runtime.security.shared.stub.javax.net.ssl.KeyManagerFactory
    at org.apache.http.conn.ssl.SSLSocketFactory.createSSLContext(SSLSocketFactory.java:221)
    at org.apache.http.conn.ssl.SSLSocketFactory.createDefaultSSLContext(SSLSocketFactory.java:359)
    at org.apache.http.conn.ssl.SSLSocketFactory.getSocketFactory(SSLSocketFactory.java:173)
    at org.apache.http.impl.conn.SchemeRegistryFactory.createDefault(SchemeRegistryFactory.java:49)
    at org.apache.http.impl.client.AbstractHttpClient.createClientConnectionManager(AbstractHttpClient.java:305)
    at org.apache.http.impl.client.AbstractHttpClient.getConnectionManager(AbstractHttpClient.java:467)
    at com.stripe.APIResource.rawRequest(Stripe.scala:120)
    at com.stripe.APIResource.request(Stripe.scala:125)
    at com.stripe.Customer$.create(Stripe.scala:242)

**Comment by ben-manes** [comment]
The following changes should be enough:

```
package object stripe {
  var apiKey: String = ""
  var connectionManager: ConnectionManager = null
}

abstract class APIResource {
  def httpClient: DefaultHttpClient = {
    ...
    return new DefaultHttpClient(httpParams, connectionManager)
  }
  ...
}
```

The constructor chain is handing null so this will have the same behavior. It provides the hook so that a client can do:

```
stripe.connectionManager = new GAEConnectionManager()
```

and it will work in AppEngine.

**Comment by ben-manes** [comment]
Closing at submitted pull request
